### ISSUE TITLE
Write various tests for a given dataset

### ISSUE THREAD

**Issue by LauraAubin** [LauraAubin/Reactoid#8]
## To-do:
- [ ] Create arrays for sample examples to be used in tests
- [ ] Supply screenshots of these array drawings
- Test that,
   - [ ] is a completed outline?
   - [ ] is not a completed outline?
   - [ ] is a completed outline after autoconnect / evaluate?
   - [ ] has too many overlaps?

**Comment by LauraAubin** [comment]
Part of https://github.com/LauraAubin/Reactoid/issues/10
